# Generated by Django 5.2.1 on 2025-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0003_alter_order_status_alter_orderdetail_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
