# Generated by Django 5.2.1 on 2025-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0004_alter_orderdetail_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product', 'color', 'size')},
        ),
    ]
