# Generated by Django 5.2.1 on 2025-06-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0005_alter_basket_unique_together_basket_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_items', to='shop_admin.color'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_items', to='shop_admin.size'),
        ),
    ]
