# Generated by Django 5.2.1 on 2025-06-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0006_alter_basket_color_alter_basket_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_admin.size'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_admin.color'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
