# Generated by Django 4.2.9 on 2025-06-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0007_orderdetail_size_alter_orderdetail_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
