# Generated by Django 4.2.9 on 2025-06-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0008_product_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
