services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app

  bot:
    build: .
    container_name: telegram_bot
    command: python Bot/main.py
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web
