version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app

  bot:
    build: .
    container_name: telegram_bot
    command: python Bot/main.py
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "9009:80"     # Docker Nginx available at http://your-server-ip:9009
      - "9443:443"    # Optional: enable if you configure SSL inside Docker
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      # These certbot paths are optional — remove if not using SSL in Docker
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web