"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from environs import Env

# Initialize environment variables
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", "django-insecure-f!ma7pm+!ge3=wey%t*-l38&o0mn8o_5u@5r%vt8fmn@w_0gh^")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)

ALLOWED_HOSTS = ['*']

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://refined-modern-rabbit.ngrok-free.app',
    'http://127.0.0.1:8000',
    "https://525a-84-54-122-26.ngrok-free.app",
    "https://django-bot.kraft-paket.uz",
    "https://admin-telegram.kraft-paket.uz",
    "https://admin1.ndc-agency.uz"
]


# Application definition

INSTALLED_APPS = [
    # Unfold admin theme
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",

    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'drf_yasg',
    "shop_admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use DATABASE_URL environment variable if available, otherwise use SQLite
DATABASES = {
    "default": env.dj_db_url(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default product image
DEFAULT_PRODUCT_IMAGE = env.str(
    "DEFAULT_PRODUCT_IMAGE",
    "https://i.pinimg.com/736x/af/c7/ae/afc7ae95091f8b0c8d6fd97d1557a138.jpg"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Unfold Admin Theme Settings
UNFOLD = {
    "SITE_TITLE": "Shop Admin",
    "SITE_HEADER": "Shop Admin",
    "SITE_URL": "/",
    "SITE_ICON": None,  # No favicon
    "DASHBOARD_CALLBACK": None,
    "STYLES": [],
    "CUSTOM_STYLE": """
        /* Import Google Material Icons */
        @import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200');

        /* Remove logos and simplify UI */
        body .unfold-header { box-shadow: none; }
        .unfold-header-logo { display: none !important; }
        .unfold-sidebar-logo { display: none !important; }
        .unfold-sidebar { border-right: 1px solid #e5e7eb; }
        .unfold-header { border-bottom: 1px solid #e5e7eb; }

        /* Material Icons styling */
        .material-symbols-outlined {
          font-family: 'Material Symbols Outlined';
          font-weight: normal;
          font-style: normal;
          font-size: 24px;
          line-height: 1;
          letter-spacing: normal;
          text-transform: none;
          display: inline-block;
          white-space: nowrap;
          word-wrap: normal;
          direction: ltr;
          -webkit-font-feature-settings: 'liga';
          -webkit-font-smoothing: antialiased;
        }
    """,
    "SCRIPTS": [],
    "TABS": [],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Products",
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/shop_admin/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/shop_admin/category/",
                    },
                    {
                        "title": "Sizes",
                        "icon": "straighten",
                        "link": "/admin/shop_admin/size/",
                    },
                    {
                        "title": "Color",
                        "icon": "straighten",
                        "link": "/admin/shop_admin/color/",
                    },
                ],
            },
            {
                "title": "Orders",
                "items": [
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": "/admin/shop_admin/order/",
                    },
                    {
                        "title": "Baskets",
                        "icon": "shopping_cart",
                        "link": "/admin/shop_admin/basket/",
                    },
                ],
            },
            {
                "title": "Users",
                "items": [
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": "/admin/shop_admin/user/",
                    },
                ],
            },
            {
                "title": "Content",
                "items": [
                    {
                        "title": "Contact Info",
                        "icon": "contact_mail",
                        "link": "/admin/shop_admin/connectus/",
                    },
                    {
                        "title": "Social Media",
                        "icon": "share",
                        "link": "/admin/shop_admin/socialmedia/",
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },
}
